### ISSUE TITLE
"Error: 'fail' size encountered."

### ISSUE THREAD

**Issue by Oded-B** [chaaz/versio#8] opened 2021-08-27 13:13 UTC
https://github.com/chaaz/versio/blob/main/src/config.rs#L1123

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by chaaz** [comment] 2021-08-30 21:27
Closing as a duplicate of #9 , which I think is the intent.

**Closed** 2021-08-30 21:27 UTC
Labels: enhancement
